import sharp from "sharp";
import { writeFileSync } from "node:fs";

const COORDS: Record<string, any> = {
  standing: { src:"/tmp/bebop-full/full.png",
    neckBase:[0.49,0.2], headTop:[0.46,0.05], shoulder:[0.5,0.235],
    elbow:[0.555,0.4], wrist:[0.575,0.55], hip:[0.4875,0.555], knee:[0.4925,0.71],
    ankle:[0.52,0.875], toe:[0.575,0.905], lw:0.045 },
  stride: { src:"/tmp/bebop-full/stride.png",
    neckBase:[0.4,0.2], headTop:[0.31,0.055], shoulder:[0.44,0.235],
    elbow:[0.58,0.34], wrist:[0.65,0.43], hip:[0.48,0.5], knee:[0.3,0.63],
    ankle:[0.19,0.83], toe:[0.12,0.88], lw:0.075 },
};

const key = process.argv[2];
const C = COORDS[key];
const meta = await sharp(C.src).metadata(); const W = meta.width!, H = meta.height!;
const PX = (p:number[]) => [p[0]*W, p[1]*H];

async function cut(A:number[], B:number[], hwFrac:number, ovTop:number, ovBot:number, extra?:number[]) {
  const [ax,ay]=PX(A), [bx,by]=PX(B); const hw = hwFrac*W;
  const xs=[ax,bx], ys=[ay,by]; if(extra){const[ex,ey]=PX(extra); xs.push(ex);ys.push(ey);}
  let x0=Math.min(...xs)-hw, x1=Math.max(...xs)+hw;
  let y0=Math.min(...ys)-ovTop*H, y1=Math.max(...ys)+ovBot*H;
  x0=Math.max(0,Math.round(x0)); y0=Math.max(0,Math.round(y0));
  x1=Math.min(W,Math.round(x1)); y1=Math.min(H,Math.round(y1));
  const cw=x1-x0, ch=y1-y0;
  const buf = await sharp(C.src).extract({left:x0,top:y0,width:cw,height:ch}).png().toBuffer();
  const top = { x:(ax-x0)/cw, y:(ay-y0)/ch }, bottom = { x:(bx-x0)/cw, y:(by-y0)/ch };
  return { uri:"data:image/png;base64,"+buf.toString("base64"), w:cw, h:ch, top, bottom, facing:"left" };
}

const hw = C.lw*0.75;
const parts:Record<string,any> = {
  head:  await cut(C.neckBase, C.headTop, C.lw*1.9, 0.025, 0.04),       // headTop..neck
  torso: await cut(C.neckBase, C.hip, C.lw*1.25, 0.0, 0.04),            // shoulders baked, narrow
  uarm:  await cut(C.shoulder, C.elbow, hw, 0.02, 0.03),
  farm:  await cut(C.elbow, C.wrist, hw*0.92, 0.03, 0.05),
  thigh: await cut(C.hip, C.knee, C.lw*0.9, 0.0, 0.03),
  shin:  await cut(C.knee, C.ankle, C.lw*0.9, 0.03, 0.02, C.toe),       // foot fused
};
const lines = Object.entries(parts).map(([n,p]:any)=>`  ${n}: { uri: "${p.uri}", w: ${p.w}, h: ${p.h}, top: { x: ${p.top.x.toFixed(4)}, y: ${p.top.y.toFixed(4)} }, bottom: { x: ${p.bottom.x.toFixed(4)}, y: ${p.bottom.y.toFixed(4)} }, facing: "left" },`);
const ts = `// AUTO-GENERATED by cut-figure.ts from /tmp/bebop-full/${key}.png — sliced from ONE figure.\nexport type Part = { uri: string; w: number; h: number; top: { x: number; y: number }; bottom: { x: number; y: number }; facing: string };\nexport const PARTS: Record<string, Part> = {\n${lines.join("\n")}\n};\n`;
const out = `/Users/serhiidubei/remotion-test/src/tower11/bebop-${key}.ts`;
writeFileSync(out, ts);
console.log("WROTE", out, "parts:", Object.entries(parts).map(([n,p]:any)=>`${n} ${p.w}x${p.h}`).join(" "));
